spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: oracle.jdbc.driver.OracleDriver
    druid:
      first:  #数据源1
        url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
#        url: jdbc:oracle:thin:@localhost:1521:gdjs
#        username: gdjs
#        password: 123456
      second:  #数据源2
        url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456

#mybatis将下划线映射到驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# dao接口debug，打印sql语句
logging:
  level:
    com.wyg.dao: debug
